#!/usr/bin/env python3
"""kat2inc.py - turn the shared frame-crypto KAT (m150/kat/group-calls-v2-frame-crypto.json)
into the C++ include api/crypto/frame_crypto_kat_vectors.inc that the P12 unittest
(FrameCryptorKat.*, T7) compiles in.

The KAT file is a byte-identical copy of the one the desktop generator
(scripts/group-e2ee-kat-dump.mjs) produces and that Android, iOS and the desktop
pin as well. Its sha256 is pinned HERE: a drifted or edited vector file fails
the step instead of quietly testing something else.

usage: kat2inc.py <kat.json> <out.inc>
       (run after m150/apply-series.sh and before `gn gen`, see test-m150-patches.yml)
exit:  0 ok | 1 pin/schema mismatch | 2 usage
"""
import hashlib
import json
import sys

# sha256 of m150/kat/group-calls-v2-frame-crypto.json (version 2). Change it only
# together with the file, and only when every consumer repo changes its pin too.
PINNED_SHA256 = "4edfef48a51fe95986e0f9f3f6568be651e45e79ff6dbab88bec48caa9ff9b38"

EXPECTED_COUNTS = {
    "cases": 102,
    "counterCases": 13,
    "replayFrames": 90,
    "replayScenarios": 13,
    "ringScenarios": 3,
}
VERDICTS = {"ok", "duplicate", "too_old", "reflected", "cap", "decrypt_failed", "missing_key"}


def die(msg, rc=1):
    sys.stderr.write("kat2inc: %s\n" % msg)
    sys.exit(rc)


def hexcheck(s, what):
    if not isinstance(s, str) or len(s) % 2 or any(c not in "0123456789abcdef" for c in s):
        die("%s is not lowercase hex" % what)
    return s


def q(s):
    # ids / names / hex only: refuse anything that would need escaping
    if not all(c.isalnum() or c in "/-_." for c in s):
        die("unexpected character in %r" % s)
    return '"%s"' % s


def codec_enum(c):
    return {"opus": "kKatOpus", "vp8": "kKatVp8", "h264": "kKatH264"}[c]


def frame_row(f, key, wire_unescaped):
    return "  {%s, %s, %d, %s, %s, %s, %uu, %uu, %uu, %s, %s, %s}," % (
        q(f["id"]),
        q(f["participantId"]),
        f["keyIndex"],
        q(key),
        codec_enum(f["codec"]),
        "true" if f["isKeyFrame"] else "false",
        f["ssrc"],
        f["rtpTimestamp"],
        f["counter"],
        q(hexcheck(f["plaintext"], f["id"] + " plaintext")),
        q(hexcheck(f["wire"], f["id"] + " wire")),
        q(hexcheck(wire_unescaped, f["id"] + " wireUnescaped")),
    )


def main():
    if len(sys.argv) != 3:
        die("usage: kat2inc.py <kat.json> <out.inc>", 2)
    path, out = sys.argv[1], sys.argv[2]
    raw = open(path, "rb").read()
    got = hashlib.sha256(raw).hexdigest()
    if got != PINNED_SHA256:
        die("%s sha256 %s != pinned %s (the shared KAT changed: update every consumer)" % (path, got, PINNED_SHA256))
    kat = json.loads(raw)
    if kat.get("version") != 2:
        die("KAT version %r != 2" % kat.get("version"))
    for k, n in EXPECTED_COUNTS.items():
        if len(kat[k]) != n:
            die("%s has %d entries, expected %d" % (k, len(kat[k]), n))
    if kat["replayRules"]["window"] != 256 or kat["replayRules"]["maxStreamsPerParticipant"] != 64:
        die("replayRules window/cap differ from 256/64")

    sender_of = {s["participantId"]: s["name"] for s in kat["senders"]}
    case_idx = {}  # "A/1/opus" -> index into cases
    L = []
    L.append("// GENERATED by m150/ci/kat2inc.py from m150/kat/group-calls-v2-frame-crypto.json")
    L.append("// (sha256 %s). Do not edit." % PINNED_SHA256)
    L.append("enum KatCodec { kKatOpus, kKatVp8, kKatH264 };")
    L.append("struct KatFrame {")
    L.append("  const char* id; const char* participant; int key_index; const char* key_hex;")
    L.append("  KatCodec codec; bool key_frame; uint32_t ssrc; uint32_t rtp_ts; uint32_t counter;")
    L.append("  const char* plaintext_hex; const char* wire_hex; const char* wire_unescaped_hex;")
    L.append("};")
    L.append("struct KatRingStep {  // kind: 0 = install, 1 = open (ok), 2 = refused")
    L.append("  int scenario; int kind; int key_index; const char* key_hex; int frame; const char* reason;")
    L.append("};")
    L.append("struct KatScenario {")
    L.append("  const char* name; const char* participant; int local_ssrc_count; uint32_t local_ssrcs[4];")
    L.append("};")
    L.append("struct KatStep {  // deliver == \"\" -> install (key_index, key_hex); else deliver + expect")
    L.append("  int scenario; const char* participant; int key_index; const char* key_hex;")
    L.append("  const char* deliver; const char* expect;")
    L.append("};")
    L.append("constexpr bool kKatPresent = true;")
    L.append("constexpr size_t kKatExpectedCases = %d;" % EXPECTED_COUNTS["cases"])
    L.append("constexpr size_t kKatExpectedCounterCases = %d;" % EXPECTED_COUNTS["counterCases"])
    L.append("constexpr size_t kKatExpectedReplayFrames = %d;" % EXPECTED_COUNTS["replayFrames"])
    L.append("constexpr size_t kKatExpectedScenarios = %d;" % EXPECTED_COUNTS["replayScenarios"])
    L.append("constexpr size_t kKatExpectedRingScenarios = %d;" % EXPECTED_COUNTS["ringScenarios"])

    # cases[]: counter 0, first frame of the ssrc
    L.append("const KatFrame kKatCases[] = {")
    for i, c in enumerate(kat["cases"]):
        ref = "%s/%d/%s" % (c["sender"], c["epoch"], c["frame"])
        case_idx[ref] = i
        f = dict(c)
        f["id"] = ref
        f["counter"] = 0
        L.append(frame_row(f, c["key"], ""))
    L.append("};")

    # counterCases[]: counter set through the sender test seam
    L.append("const KatFrame kKatCounterCases[] = {")
    for c in kat["counterCases"]:
        wu = c.get("wireUnescaped", "")
        L.append(frame_row(c, c["key"], wu))
    L.append("};")

    # replay frame pool
    pool_idx = {}
    L.append("const KatFrame kKatReplayFrames[] = {")
    for i, f in enumerate(kat["replayFrames"]):
        if f["codec"] != "opus":
            die("replay pool frame %s is not opus" % f["id"])
        pool_idx[f["id"]] = i
        L.append(frame_row(f, "", ""))
    L.append("};")

    # ring scenarios (every frame there has counter 0 on the same ssrc: the C++
    # side opens each one on a fresh provider holding the keys installed so far)
    L.append("const KatScenario kKatRingScenarios[] = {")
    for s in kat["ringScenarios"]:
        L.append("  {%s, %s, 0, {0, 0, 0, 0}}," % (q(s["name"]), q(s["participantId"])))
    L.append("};")
    L.append("const KatRingStep kKatRingSteps[] = {")
    for si, s in enumerate(kat["ringScenarios"]):
        sender = sender_of[s["participantId"]]
        for st in s["steps"]:
            for epoch in st["install"]:
                key = [c for c in kat["cases"] if c["sender"] == sender and c["epoch"] == epoch][0]
                L.append("  {%d, 0, %d, %s, -1, \"\"}," % (si, key["keyIndex"], q(key["key"])))
            for ref in st["opens"]:
                L.append("  {%d, 1, 0, \"\", %d, \"\"}," % (si, case_idx[ref]))
            for r in st["refused"]:
                if r["reason"] not in VERDICTS:
                    die("unknown ring verdict %s" % r["reason"])
                L.append("  {%d, 2, 0, \"\", %d, %s}," % (si, case_idx[r["frame"]], q(r["reason"])))
    L.append("};")

    # replay scenarios, flattened
    L.append("const KatScenario kKatScenarios[] = {")
    for s in kat["replayScenarios"]:
        loc = s["localSendSsrcs"]
        if len(loc) > 4:
            die("scenario %s has more than 4 local ssrcs" % s["name"])
        pad = ", ".join(["%uu" % x for x in loc] + ["0"] * (4 - len(loc)))
        L.append("  {%s, %s, %d, {%s}}," % (q(s["name"]), q(s["participantId"]), len(loc), pad))
    L.append("};")
    L.append("const KatStep kKatSteps[] = {")
    for si, s in enumerate(kat["replayScenarios"]):
        for st in s["steps"]:
            part = st["participant"]
            if "install" in st:
                for ins in st["install"]:
                    L.append("  {%d, %s, %d, %s, \"\", \"\"}," % (si, q(part), ins["keyIndex"], q(hexcheck(ins["key"], "install key"))))
            else:
                if st["expect"] not in VERDICTS:
                    die("unknown verdict %s" % st["expect"])
                if st["deliver"] not in pool_idx:
                    die("scenario %s delivers unknown frame %s" % (s["name"], st["deliver"]))
                L.append("  {%d, %s, 0, \"\", %s, %s}," % (si, q(part), q(st["deliver"]), q(st["expect"])))
    L.append("};")
    L.append("")
    open(out, "w", newline="\n").write("\n".join(L))
    print("kat2inc: wrote %s (%d cases, %d counterCases, %d replay frames, %d scenarios)" % (
        out, len(kat["cases"]), len(kat["counterCases"]), len(kat["replayFrames"]), len(kat["replayScenarios"])))


if __name__ == "__main__":
    main()
